caches:
  - registry: "~"
    id: "node"
    key: '{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum "package-lock.json" }}'
    fallback_keys:
      - '{{ id }}-{{ agent.os }}-{{ agent.arch }}-'
    paths:
      - node_modules
