
common:
  - zipstash_pkg_plugin: &zstash-node
      .buildkite/plugins/zstash:
        id: "node"
        key: "{{ id }}-{{ checksum 'package-lock.json' }}"
        paths: |
          node_modules
        endpoint: $ENDPOINT
        bucket-url: $BUCKET_URL

steps:

  - command: npm install
    plugins:
      - *zstash-node
    key: npm-install

  - command: npm test
    plugins:
      - *zstash-node
    key: npm-test
    depends_on: [npm-install]

