common:
  - zipstash_pkg_plugin: &zstash-node
      .buildkite/plugins/zstash:
        ids: "node"
  -  docker-compose_plugin: &docker-compose
      docker-compose#v5.2.0:
        config: .buildkite/docker-compose.yaml
        run: node
        tty: true
        mount-buildkite-agent: true

steps:
  - group: "With cache"
    steps:
      - command: npm install
        plugins:
          - *zstash-node
          - *docker-compose
        key: npm-install

      - command: npm test
        plugins:
          - *zstash-node
          - *docker-compose
        key: npm-test
        depends_on: [npm-install]

      - label: "Install (with cache)"
        command: npm run build
        plugins:
          - *zstash-node
          - *docker-compose
        key: npm-install-cached
        depends_on: [npm-install]

  - group: "Without cache"
    steps:
      - command: npm install
        plugins:
          - *docker-compose
        key: npm-install-uncached

      - command: 
        - npm install
        - npm test
        plugins:
          - *docker-compose
        key: npm-test-uncached
        depends_on: [npm-install-uncached]
