common:
  - zipstash_pkg_plugin: &zstash-node
      .buildkite/plugins/zstash:
        id: "node"
        key: '{{ id }}-{{ agent.os }}-{{ agent.arch }}-{{ checksum "package-lock.json" }}'
        paths: |
          node_modules
        endpoint: $ENDPOINT
        bucket-url: $BUCKET_URL
  -  docker-compose#v5.2.0: &docker-compose
      config: .buildkite/docker-compose.yaml
      run: golangci-lint
      tty: true
      mount-buildkite-agent: true


steps:
  - group: "With cache"
    steps:
      - command: .buildkite/scripts/npm-install-no-cache.sh
        plugins:
          - *zstash-node
          - *docker-compose
        key: npm-install

      - command: npm test
        plugins:
          - *zstash-node
          - *docker-compose
        key: npm-test
        depends_on: [npm-install]

      - label: "Install (with cache)"
        command: npm run build
        plugins:
          - *zstash-node
          - *docker-compose
        key: npm-install-cached
        depends_on: [npm-install]

  - group: "Without cache"
    steps:
      - command: .buildkite/scripts/npm-install-no-cache.sh
        plugins:
          - *docker-compose
        key: npm-install-uncached

      - command: 
        - .buildkite/scripts/npm-install-no-cache.sh
        - npm test
        plugins:
          - *docker-compose
        key: npm-test-uncached
        depends_on: [npm-install-uncached]
