#!/usr/bin/env bash
set -euo pipefail

BK_ZSTASH_BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && cd .. && pwd)"
source "${BK_ZSTASH_BASEDIR}/lib/shared.bash"

CACHE_KEY="$(expand_templates "$BUILDKITE_PLUGIN_ZSTASH_KEY")"

BK_ZSTASH_ID="${BUILDKITE_PLUGIN_ZSTASH_ID:-}"

cache_result=$(buildkite-agent meta-data get "zstash.restore.${BK_ZSTASH_ID}.result")

BK_ZSTASH_SKIP=${cache_result:-false}

zstash save \
  --endpoint "${BUILDKITE_PLUGIN_ZSTASH_ENDPOINT}" \
  --key "${CACHE_KEY}" \
  --bucket-url "${BUILDKITE_PLUGIN_ZSTASH_BUCKET_URL}" \
  --paths "${BUILDKITE_PLUGIN_ZSTASH_PATHS}" \
  --skip="${BK_ZSTASH_SKIP}"
