#!/usr/bin/env bash
set -euo pipefail
shopt -s lastpipe


if [ -n "${BUILDKITE_PLUGIN_ZSTASH_IDS:-}" ]; then
  zstash restore --ids "${BUILDKITE_PLUGIN_ZSTASH_IDS}" | read cache_result
else
  zstash restore | read cache_result
fi

echo "Cache HIT: ${cache_result}"
