#!/usr/bin/env bash
set -euo pipefail
shopt -s lastpipe

BK_ZSTASH_ID="${BUILDKITE_PLUGIN_ZSTASH_ID:-}"

zstash restore \
  --endpoint "${BUILDKITE_PLUGIN_ZSTASH_ENDPOINT}" \
  --key "${BUILDKITE_PLUGIN_ZSTASH_KEY}" \
  --bucket-url "${BUILDKITE_PLUGIN_ZSTASH_BUCKET_URL}" \
  --paths "${BUILDKITE_PLUGIN_ZSTASH_PATHS}" | read cache_result

echo "Cache HIT: ${cache_result}"

buildkite-agent meta-data set "zstash.restore.${BK_ZSTASH_ID}.result" "${cache_result}"
